"""Create all table

Revision ID: 5ee2e06cd0d3
Revises:
Create Date: 2025-12-17 16:36:55.787367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ee2e06cd0d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "video_created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("reports_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_index(
        op.f("ix_videos_creator_id"), "videos", ["creator_id"], unique=False
    )
    op.create_table(
        "video_snapshots",
        sa.Column("video_id", sa.UUID(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("reports_count", sa.Integer(), nullable=False),
        sa.Column("delta_views_count", sa.Integer(), nullable=False),
        sa.Column("delta_likes_count", sa.Integer(), nullable=False),
        sa.Column("delta_comments_count", sa.Integer(), nullable=False),
        sa.Column("delta_reports_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_snapshots_video_id_videos"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_snapshots")),
    )
    op.create_index(
        op.f("ix_video_snapshots_created_at"),
        "video_snapshots",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_snapshots_created_at"), table_name="video_snapshots")
    op.drop_table("video_snapshots")
    op.drop_index(op.f("ix_videos_creator_id"), table_name="videos")
    op.drop_table("videos")
    # ### end Alembic commands ###
